(function() {
  const translations = {
    en: {
      'nav-features': 'Features',
      'nav-about': 'About Us',
      'nav-project': 'Our Project',
      'nav-team': 'Team',
      'hero-title': 'Your Motorcycle, <span class="text-primary">Smarter</span>.',
      'hero-subtitle': 'Connect your bike to the digital world for enhanced safety, performance, and peace of mind.',
      'btn-start': 'Go to Web <span class="material-icons ml-2">web</span>',
      'btn-mobile': 'Go to Mobile App <span class="material-icons ml-2">smartphone</span>',
      'btn-explore': 'Explore <span class="material-icons ml-2">arrow_downward</span>',
      'features-title': 'Features',
      'features-desc': 'Everything you need to stay connected and safe on the road.',
      'feature1-title': 'Real-Time Monitoring',
      'feature1-desc': 'Track fuel, engine temp, tire pressure, and more, all from your phone.',
      'feature2-title': 'Preventive Alerts',
      'feature2-desc': 'Get notified before a small issue becomes a big problem for you and your mechanic.',
      'feature3-title': 'Service History',
      'feature3-desc': 'Keep a digital log of all repairs, services, and expenses in one place.',
      'feature4-title': 'Mechanic Connection',
      'feature4-desc': 'Share live data with your trusted mechanic for faster, more accurate diagnostics.',
      'feature5-title': 'Health Reports',
      'feature5-desc': 'Automatically generate vehicle health reports to track performance over time.',
      'feature6-title': 'Enhanced Security',
      'feature6-desc': 'Anticipate failures and ride with confidence knowing your bike is being watched.',
      'about-title': 'Our Mission and Vision',
      'mission-title': 'Mission',
      'mission-text': 'Transform motorcycle management by combining IoT technology and data analytics to deliver safety, efficiency, and confidence to owners and mechanics.',
      'vision-title': 'Vision',
      'vision-text': 'To be the leading smart mobility platform that revolutionizes preventive maintenance and connectivity in the two-wheel ecosystem.',
      'project-title': 'Our Project',
      'team-title': 'Meet the Team',
      'team-role-1': 'Lead Architect',
      'team-role-2': 'Project Manager',
      'team-role-3': 'Frontend Developer',
      'team-role-4': 'Backend Developer',
      'team-role-5': 'IoT Specialist',
      'team-role-6': 'UI/UX Designer',
      'cta-title': 'Upgrade your bike to the next level.',
      'cta-text': 'Join the Octane community and experience the future of motorcycling.',
      'btn-get-started': '<span class="material-icons ml-2">two_wheeler</span>\n                            Get Started',
      'btn-contact-sales': '<span class="material-icons ml-2">contact_support</span>\n                            Contact Sales',
      'footer-features': 'Features',
      'footer-about': 'About Us',
      'footer-team': 'Team',
      'footer-terms': 'Terms of Service',
      'nav-plans': 'Plans',
      'footer-plans': 'Plans',
      'plans-title': 'Plans',
      'plans-desc': 'Choose the plan that fits your workshop.',
      'plan-bronze-name': 'Bronze',
      'plan-bronze-price': 'Estimated price: S/ 49.90/month',
      'plan-bronze-ideal': 'Ideal for: Beginning independent mechanics',
      'plan-bronze-clients': 'Max. clients: 50',
      'plan-bronze-storage': 'Storage: 1TB',
      'plan-silver-name': 'Silver',
      'plan-silver-price': 'Estimated price: S/ 99.90/month',
      'plan-silver-ideal': 'Ideal for: Established workshops',
      'plan-silver-clients': 'Max. clients: 200',
      'plan-silver-storage': 'Storage: 8TB',
      'plan-black-name': 'Black',
      'plan-black-price': 'Estimated price: S/ 149.90/month',
      'plan-black-ideal': 'Ideal for: Workshops with multiple mechanics',
      'plan-black-clients': 'Max. clients: 500',
      'plan-black-storage': 'Storage: 20TB',
      'footer-copyright': '© 2025 NRG6. All rights reserved.',
      'terms-title': 'Terms and Conditions',
      'terms-updated': 'Last updated: October 31, 2025',
      'terms-section1-title': '1. Acceptance of Terms',
      'terms-section1-text': 'By accessing and using Octane\'s services, you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, you may not use our services.',
      'terms-section2-title': '2. Service Description',
      'terms-section2-text': 'Octane provides IoT-based motorcycle management services, including real-time monitoring, preventive alerts, service history tracking, and mechanic connectivity features. Our platform is designed to enhance safety, performance, and maintenance efficiency for motorcycle owners and mechanics.',
      'terms-section3-title': '3. User Responsibilities',
      'terms-section3-li1': 'You must provide accurate and complete information during registration',
      'terms-section3-li2': 'You are responsible for maintaining the security of your account credentials',
      'terms-section3-li3': 'You must ensure proper installation and maintenance of IoT devices',
      'terms-section3-li4': 'You agree not to misuse the service or interfere with its normal operation',
      'terms-section3-li5': 'You must comply with all applicable laws and regulations while using our services',
      'terms-section4-title': '4. Subscription and Payment',
      'terms-section4-text': 'Services are provided on a subscription basis with three tiers: Bronze, Silver, and Black. Pricing is as indicated in the Plans section of our website. Payments are processed monthly and are non-refundable unless otherwise required by law. We reserve the right to modify pricing with 30 days\' advance notice to subscribers.',
      'terms-section5-title': '5. Data Privacy and Security',
      'terms-section5-text': 'We collect and process data from your motorcycle\'s IoT devices for service provision and performance optimization. We are committed to protecting your privacy and will not share your personal data with third parties without your explicit consent, except as required by law. All data is stored securely and encrypted according to industry standards.',
      'terms-section6-title': '6. Limitation of Liability',
      'terms-section6-text': 'Octane provides monitoring and alerting services but is not responsible for mechanical failures, accidents, damages, or any consequences resulting from the use or misuse of our services. Users should always follow proper maintenance schedules and professional advice from qualified mechanics. Our service is intended to assist and enhance, not replace, professional mechanical expertise.',
      'terms-section7-title': '7. IoT Device Usage',
      'terms-section7-text': 'The IoT devices provided must be installed by qualified professionals. Improper installation or tampering with devices may void your warranty and subscription. Octane is not liable for damages resulting from unauthorized modifications or misuse of equipment.',
      'terms-section8-title': '8. Service Modifications',
      'terms-section8-text': 'We reserve the right to modify, suspend, or discontinue any part of the service at any time with reasonable notice to users. We will make efforts to ensure service continuity and minimize disruptions.',
      'terms-section9-title': '9. Mechanic Partnership',
      'terms-section9-text': 'Mechanics using our platform must maintain appropriate licenses and certifications. Octane acts as a facilitator for connection between motorcycle owners and mechanics but does not guarantee the quality of service provided by third-party mechanics.',
      'terms-section10-title': '10. Termination',
      'terms-section10-text': 'Either party may terminate the service agreement with 30 days\' notice. Octane reserves the right to immediately terminate accounts that violate these terms. Upon termination, access to the platform and stored data will be revoked after a 30-day grace period.',
      'terms-section11-title': '11. Intellectual Property',
      'terms-section11-text': 'All content, trademarks, logos, and intellectual property on the Octane platform are owned by NRG6. Users may not reproduce, distribute, or create derivative works without express written permission.',
      'terms-section12-title': '12. Contact Information',
      'terms-section12-text': 'For questions regarding these Terms and Conditions, please contact us through our support channels or visit our website for more information.',
      'terms-back-btn': 'Back to Home'
    },
    es: {
      'nav-features': 'Características',
      'nav-about': 'Sobre Nosotros',
      'nav-project': 'Nuestro Proyecto',
      'nav-team': 'Equipo',
      'hero-title': 'Tu motocicleta, <span class="text-primary">más inteligente</span>.',
      'hero-subtitle': 'Conecta tu moto al mundo digital para mayor seguridad, rendimiento y tranquilidad.',
      'btn-start': 'Ir a Web <span class="material-icons ml-2">web</span>',
      'btn-mobile': 'Ir a la App Móvil <span class="material-icons ml-2">smartphone</span>',
      'btn-explore': 'Explorar <span class="material-icons ml-2">arrow_downward</span>',
      'features-title': 'Características',
      'features-desc': 'Todo lo que necesitas para mantenerte conectado y seguro en la carretera.',
      'feature1-title': 'Monitoreo en tiempo real',
      'feature1-desc': 'Controla combustible, temperatura del motor, presión de llantas y más, todo desde tu teléfono.',
      'feature2-title': 'Alertas preventivas',
      'feature2-desc': 'Recibe notificaciones antes de que un pequeño problema se convierta en uno mayor para ti y tu mecánico.',
      'feature3-title': 'Historial de servicios',
      'feature3-desc': 'Lleva un registro digital de reparaciones, servicios y gastos en un solo lugar.',
      'feature4-title': 'Conexión con el mecánico',
      'feature4-desc': 'Comparte datos en vivo con tu mecánico de confianza para diagnósticos más rápidos y precisos.',
      'feature5-title': 'Reportes de salud',
      'feature5-desc': 'Genera automáticamente reportes de salud del vehículo para seguir el rendimiento en el tiempo.',
      'feature6-title': 'Seguridad mejorada',
      'feature6-desc': 'Anticipa fallas y conduce con confianza sabiendo que tu moto está siendo monitoreada.',
      'about-title': 'Nuestra Misión y Visión',
      'mission-title': 'Misión',
      'mission-text': 'Transformar la gestión de motocicletas combinando tecnología IoT y análisis de datos para ofrecer seguridad, eficiencia y confianza a propietarios y mecánicos.',
      'vision-title': 'Visión',
      'vision-text': 'Ser la plataforma líder en movilidad inteligente que revolucione el mantenimiento preventivo y la conexión en el ecosistema de vehículos de dos ruedas.',
      'project-title': 'Nuestro Proyecto',
      'team-title': 'Conoce al Equipo',
      'team-role-1': 'Arquitecto Principal',
      'team-role-2': 'Gerente de Proyecto',
      'team-role-3': 'Desarrollador Frontend',
      'team-role-4': 'Desarrollador Backend',
      'team-role-5': 'Especialista IoT',
      'team-role-6': 'Diseñador UI/UX',
      'cta-title': 'Lleva tu moto al siguiente nivel.',
      'cta-text': 'Únete a la comunidad Octane y experimenta el futuro del motociclismo.',
      'btn-get-started': '<span class="material-icons ml-2">two_wheeler</span>\n                            Comenzar',
      'btn-contact-sales': '<span class="material-icons ml-2">contact_support</span>\n                            Contactar Ventas',
      'footer-features': 'Características',
      'footer-about': 'Sobre Nosotros',
      'footer-team': 'Equipo',
      'footer-terms': 'Términos del Servicio',
      'nav-plans': 'Planes',
      'footer-plans': 'Planes',
      'plans-title': 'Planes',
      'plans-desc': 'Elige el plan que se adapta a tu taller.',
      'plan-bronze-name': 'Bronce',
      'plan-bronze-price': 'Precio estimado: S/ 49.90/mes',
      'plan-bronze-ideal': 'Ideal para: Mecánicos independientes que empiezan',
      'plan-bronze-clients': 'Máx. clientes: 50',
      'plan-bronze-storage': 'Almacenamiento: 1TB',
      'plan-silver-name': 'Plata',
      'plan-silver-price': 'Precio estimado: S/ 99.90/mes',
      'plan-silver-ideal': 'Ideal para: Talleres establecidos',
      'plan-silver-clients': 'Máx. clientes: 200',
      'plan-silver-storage': 'Almacenamiento: 8TB',
      'plan-black-name': 'Black',
      'plan-black-price': 'Precio estimado: S/ 149.90/mes',
      'plan-black-ideal': 'Ideal para: Talleres con múltiples mecánicos',
      'plan-black-clients': 'Máx. clientes: 500',
      'plan-black-storage': 'Almacenamiento: 20TB',
      'footer-copyright': '© 2025 NRG6. Todos los derechos reservados.',
      'terms-title': 'Términos y Condiciones',
      'terms-updated': 'Última actualización: 31 de octubre de 2025',
      'terms-section1-title': '1. Aceptación de los Términos',
      'terms-section1-text': 'Al acceder y utilizar los servicios de Octane, acepta estar sujeto a estos Términos y Condiciones. Si no está de acuerdo con alguna parte de estos términos, no puede utilizar nuestros servicios.',
      'terms-section2-title': '2. Descripción del Servicio',
      'terms-section2-text': 'Octane proporciona servicios de gestión de motocicletas basados en IoT, incluido el monitoreo en tiempo real, alertas preventivas, seguimiento del historial de servicio y funciones de conectividad con mecánicos. Nuestra plataforma está diseñada para mejorar la seguridad, el rendimiento y la eficiencia del mantenimiento para propietarios de motocicletas y mecánicos.',
      'terms-section3-title': '3. Responsabilidades del Usuario',
      'terms-section3-li1': 'Debe proporcionar información precisa y completa durante el registro',
      'terms-section3-li2': 'Es responsable de mantener la seguridad de sus credenciales de cuenta',
      'terms-section3-li3': 'Debe asegurar la instalación y el mantenimiento adecuado de los dispositivos IoT',
      'terms-section3-li4': 'Acepta no hacer un mal uso del servicio ni interferir con su funcionamiento normal',
      'terms-section3-li5': 'Debe cumplir con todas las leyes y regulaciones aplicables al usar nuestros servicios',
      'terms-section4-title': '4. Suscripción y Pago',
      'terms-section4-text': 'Los servicios se proporcionan mediante suscripción con tres niveles: Bronce, Plata y Black. Los precios se indican en la sección de Planes de nuestro sitio web. Los pagos se procesan mensualmente y no son reembolsables, salvo que la ley exija lo contrario. Nos reservamos el derecho de modificar los precios con 30 días de aviso previo a los suscriptores.',
      'terms-section5-title': '5. Privacidad y Seguridad de Datos',
      'terms-section5-text': 'Recopilamos y procesamos datos de los dispositivos IoT de su motocicleta para la provisión de servicios y optimización del rendimiento. Estamos comprometidos a proteger su privacidad y no compartiremos sus datos personales con terceros sin su consentimiento explícito, excepto cuando lo exija la ley. Todos los datos se almacenan de forma segura y se cifran según los estándares de la industria.',
      'terms-section6-title': '6. Limitación de Responsabilidad',
      'terms-section6-text': 'Octane proporciona servicios de monitoreo y alertas, pero no es responsable de fallas mecánicas, accidentes, daños o cualquier consecuencia derivada del uso o mal uso de nuestros servicios. Los usuarios siempre deben seguir los programas de mantenimiento adecuados y el asesoramiento profesional de mecánicos calificados. Nuestro servicio está destinado a asistir y mejorar, no a reemplazar, la experiencia mecánica profesional.',
      'terms-section7-title': '7. Uso de Dispositivos IoT',
      'terms-section7-text': 'Los dispositivos IoT proporcionados deben ser instalados por profesionales calificados. La instalación incorrecta o la manipulación de los dispositivos puede anular su garantía y suscripción. Octane no es responsable de los daños resultantes de modificaciones no autorizadas o mal uso del equipo.',
      'terms-section8-title': '8. Modificaciones del Servicio',
      'terms-section8-text': 'Nos reservamos el derecho de modificar, suspender o descontinuar cualquier parte del servicio en cualquier momento con aviso razonable a los usuarios. Haremos esfuerzos para garantizar la continuidad del servicio y minimizar las interrupciones.',
      'terms-section9-title': '9. Asociación con Mecánicos',
      'terms-section9-text': 'Los mecánicos que utilizan nuestra plataforma deben mantener las licencias y certificaciones apropiadas. Octane actúa como facilitador de la conexión entre propietarios de motocicletas y mecánicos, pero no garantiza la calidad del servicio proporcionado por mecánicos de terceros.',
      'terms-section10-title': '10. Terminación',
      'terms-section10-text': 'Cualquiera de las partes puede terminar el acuerdo de servicio con un aviso de 30 días. Octane se reserva el derecho de terminar inmediatamente las cuentas que violen estos términos. Tras la terminación, el acceso a la plataforma y a los datos almacenados se revocará después de un período de gracia de 30 días.',
      'terms-section11-title': '11. Propiedad Intelectual',
      'terms-section11-text': 'Todo el contenido, marcas comerciales, logotipos y propiedad intelectual en la plataforma Octane son propiedad de NRG6. Los usuarios no pueden reproducir, distribuir o crear obras derivadas sin permiso expreso por escrito.',
      'terms-section12-title': '12. Información de Contacto',
      'terms-section12-text': 'Para preguntas sobre estos Términos y Condiciones, comuníquese con nosotros a través de nuestros canales de soporte o visite nuestro sitio web para obtener más información.',
      'terms-back-btn': 'Volver al Inicio'
    }
  };

  const htmlKeys = new Set(['hero-title','btn-start','btn-mobile','btn-explore','btn-get-started','btn-contact-sales']);

  function setLanguage(lang) {
    const dict = translations[lang] || translations.en;
    Object.keys(dict).forEach(function(id){
      const el = document.getElementById(id);
      if (!el) return;
      if (htmlKeys.has(id)) {
        el.innerHTML = dict[id];
      } else {
        el.textContent = dict[id];
      }
    });
    document.documentElement.setAttribute('lang', lang);
    const select = document.getElementById('language-select');
    if (select) select.value = lang;
    try { localStorage.setItem('lang', lang); } catch(e) {}
  }

  function detectLang() {
    try {
      const saved = localStorage.getItem('lang');
      if (saved) return saved;
    } catch(e) {}
    const nav = (navigator.language || '').toLowerCase();
    return nav.startsWith('es') ? 'es' : 'en';
  }

  document.addEventListener('DOMContentLoaded', function(){
    const lang = detectLang();
    setLanguage(lang);
    const select = document.getElementById('language-select');
    if (select) {
      select.addEventListener('change', function(e){ setLanguage(e.target.value); });
    }
  });
})();
